name: Validate_Azure_Credentials

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 13 * * 1,2,3,4,5'
  workflow_dispatch:

jobs:

  Validate-Azure-Credentials:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SUPER_SP1 }}

  Trigger-API-SendEmail:
    if: ${{ failure() }}
    needs:  Validate-Azure-Credentials
    runs-on: ubuntu-latest
    steps:
      - name: call httprequest_action v2
        uses: oaviles/httprequest_action@v2
        with:
          url: ${{ secrets.API_URL }}
          path: ${{ secrets.API_PATH }}
          key: ${{ secrets.API_KEY }}
        
      - name: Get the output status
        run: echo "Status Code ${{ steps.javascriptaction.outputs.status }}"
        
  Azure-Credential-is-Working:
    if: ${{ success() }}
    needs:  Validate-Azure-Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Azure Credential is Working
        run: echo Azure Credential is Working!
